Repository UnblockNeteaseMusic/server, pull requests merged in 2021-09, with the labels that each got.

#129 style: with prettier
  .github/workflows/prettier.yml
  src/provider/kuwo.js
Labels: style

#130 style: with prettier
  .github/workflows/test-source.yml
  README.md
  jest.config.js
  package.json
Labels: style

#123 Add source: yt-download.org
  src/consts.js
  src/provider/match.js
  src/provider/yt-download.js
  src/server.js
Labels: enhancement

#134 style: with prettier
  src/provider/match.js
  src/provider/yt-download.js
Labels: style

#135 style: with prettier
  README.md
  src/app.js
Labels: style

#139 style: with prettier
  src/app.js
Labels: style

#153 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
  precompiled/bridge.js
Labels: ci:style, ci:build

#159 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
  precompiled/bridge.js
Labels: ci:build

#161 style: with prettier
  src/provider/match.js
Labels: ci:style

#162 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
  precompiled/bridge.js
Labels: ci:build

#163 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
Labels: ci:build

#165 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
  precompiled/bridge.js
Labels: ci:build

#166 add local vip
  README.md
  src/hook.js
Labels: enhancement

#169 style: with prettier
  src/hook.js
Labels: ci:style

#175 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
  precompiled/bridge.js
Labels: ci:build

#178 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
  precompiled/bridge.js
Labels: ci:build

#188 style: with prettier
  src/provider/youtube.js
Labels: ci:style

#189 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
  precompiled/bridge.js
Labels: ci:build

#191 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
Labels: ci:build

#200 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
  precompiled/bridge.js
Labels: ci:build

#204 style: with prettier
  README.md
Labels: ci:style

#209 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
  precompiled/bridge.js
Labels: ci:build

#211 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
Labels: ci:build

#212 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
Labels: ci:build

#217 build(precompiled): make a bundle with the dependencies
  precompiled/app.js
Labels: ci:build
